export const SET_MAINALBUMS = 'SET_MAINALBUMS'

export const SET_MAINSKIP = 'SET_MAINSKIP'

export const SET_MAINTOP = 'SET_MAINTOP'

export const SET_SEARCHCATEGORIES = 'SET_SEARCHCATEGORIES'

export const SET_SEARCHDATA = 'SET_SEARCHDATA'

export const SET_SEARCHSKIP = 'SET_SEARCHSKIP'

export const SET_SEARCHCATEGORIES_NAME = 'SET_SEARCHCATEGORIES_NAME'
